/**
 * 需求4 T13 的逐文件分类清单。
 *
 * core 只放稳定安全/数据/媒体/operation/排序不变量；smoke 是独立小旅程。
 * 历史实现型覆盖已经完成退役。新增测试文件必须先在这里归类。
 */
export const coreTestFiles = [
  'tests/unit/admin-upload-session.test.ts',
  'tests/unit/admin-media-preview.test.ts',
  'tests/unit/analytics.test.ts',
  'tests/unit/auth.test.ts',
  'tests/unit/client-address.test.ts',
  'tests/unit/commission-retention-cli.test.ts',
  'tests/unit/contact-qr-link.test.ts',
  'tests/unit/contracts.test.ts',
  'tests/unit/deployment-contract.test.ts',
  'tests/unit/error-reason.test.ts',
  'tests/unit/md5.test.ts',
  'tests/unit/media-mapper.test.ts',
  'tests/unit/media-storage.test.ts',
  'tests/unit/price.test.ts',
  'tests/unit/privacy-policy-readiness.test.ts',
  'tests/unit/production-guard.test.ts',
  'tests/unit/public-media-cache.test.ts',
  'tests/unit/public-pagination.test.ts',
  'tests/unit/public-search.test.ts',
  'tests/unit/public-sources.test.ts',
  'tests/unit/r3-stage-a-remote-cleanup.test.ts',
  'tests/unit/request-body.test.ts',
  'tests/unit/router-scroll-behavior.test.ts',
  'tests/unit/runtime-boundaries.test.ts',
  'tests/unit/search.test.ts',
  'tests/unit/site-content.test.ts',
  'tests/unit/site-display-recipe.test.ts',
  'tests/unit/third-party-notices.test.ts',
  'tests/unit/work-form.test.ts',
  'tests/integration/adoption-projection.test.ts',
  'tests/integration/analytics.test.ts',
  'tests/integration/auth-api.test.ts',
  'tests/integration/auth-core.test.ts',
  'tests/integration/commission-retention.test.ts',
  'tests/integration/commission-confirmation.test.ts',
  'tests/integration/database.test.ts',
  'tests/integration/domain-schema.test.ts',
  'tests/integration/health.test.ts',
  'tests/integration/media-completion.test.ts',
  'tests/integration/media-recipe.test.ts',
  'tests/integration/operation-interrupt.test.ts',
  'tests/integration/operation-lease.test.ts',
  'tests/integration/public-site-contracts.test.ts',
  'tests/integration/r3-adoption-expand.test.ts',
  'tests/integration/r3-commission-contract.test.ts',
  'tests/integration/r3-commission-follow-up.test.ts',
  'tests/integration/r3-hero-collection-publication.test.ts',
  'tests/integration/r3-hero-expand.test.ts',
  'tests/integration/r3-stage-a-cleanup.test.ts',
  'tests/integration/r3-works-contract.test.ts',
  'tests/integration/readiness.test.ts',
  'tests/integration/upload-session.test.ts',
  'tests/integration/watermark-branding.test.ts',
  'tests/integration/work-management.test.ts',
  'tests/integration/work-publication.test.ts',
] as const

export const smokeTestFiles = [
  'tests/smoke/main-journeys.spec.ts',
] as const
