export const ADMIN_MEDIA_CARD_PREVIEW_WIDTH = 320
export const ADMIN_MEDIA_EDITOR_PREVIEW_WIDTH = 640

export const ADMIN_MEDIA_PREVIEW_WIDTHS = [
  ADMIN_MEDIA_CARD_PREVIEW_WIDTH,
  ADMIN_MEDIA_EDITOR_PREVIEW_WIDTH,
] as const

export type AdminMediaPreviewWidth = typeof ADMIN_MEDIA_PREVIEW_WIDTHS[number]
